'use client';

import React, { useEffect, useState } from 'react';
import { Download, Users, Package, Leaf, DollarSign, ClipboardCheck, AlertCircle } from 'lucide-react';

type Insights = { workspace: { name: string; type: string; description?: string; members: { name: string; role: string }[] }; inventory: { totalItems: number; uniqueTypes: number; reusableValue: number; untestedItems: number; conditions: Record<string, number>; categories: Record<string, number> }; activity: { reusedComponents: number; completedProjects: number; activeProjects: number; events: { type: string; date: string; detail: string; quantity: number }[] }; impact: { massKg: number; avoidedCost: number; methodology: string; coverage: number }; recommendations: string[] };

function Metric({ label, value, detail, icon: Icon }: { label: string; value: string; detail: string; icon: React.ElementType }) {
  return <div className="bg-white rounded-3xl border border-[#E5EDE8] p-5 shadow-xs space-y-3"><div className="w-9 h-9 rounded-xl bg-[#E4FA8A] text-[#0F382A] flex items-center justify-center"><Icon className="w-4 h-4" /></div><div><div className="text-2xl font-serif text-[#11221B]">{value}</div><div className="text-[10px] font-mono uppercase tracking-wider text-[#5A6B63] mt-1">{label}</div></div><p className="text-xs text-[#7E9187]">{detail}</p></div>;
}

export default function ClassroomPage() {
  const [data, setData] = useState<Insights | null>(null); const [error, setError] = useState(false);
  useEffect(() => { fetch('/api/classroom').then((r) => r.ok ? r.json() : Promise.reject()).then(setData).catch(() => setError(true)); }, []);
  const maxCategory = data ? Math.max(...Object.values(data.inventory.categories), 1) : 1;
  return <div className="space-y-6 max-w-5xl animate-in fade-in duration-300">
    <div className="flex items-start justify-between gap-4 flex-wrap"><div><div className="text-[11px] font-mono uppercase tracking-widest text-[#5A6B63] font-medium mb-1">Institutional insights · Phase 3</div><h1 className="text-3xl md:text-4xl font-serif text-[#11221B] tracking-tight">Classroom & teams</h1><p className="text-sm text-[#5A6B63] mt-1">A scoped view of shared salvage inventory, reuse activity, and lab progress.</p></div><a href="/api/classroom?format=csv" className="inline-flex items-center gap-2 rounded-xl bg-[#0F382A] text-white px-4 py-2.5 text-xs font-semibold hover:bg-[#144232]"><Download className="w-4 h-4 text-[#D4F55C]" />Export inventory CSV</a></div>
    {!data && !error && <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">{[1,2,3,4].map((n) => <div key={n} className="h-36 rounded-3xl bg-white border border-[#E5EDE8] animate-pulse" />)}</div>}
    {error && <div className="bg-white border border-[#E5EDE8] rounded-3xl p-10 text-center"><AlertCircle className="w-7 h-7 text-[#5A6B63] mx-auto mb-2" /><p className="font-serif text-[#11221B]">Lab demo data is unavailable.</p><p className="text-xs text-[#7E9187] mt-1">Run the seed command to restore the demonstrable ECE lab workspace.</p></div>}
    {data && <><section className="bg-[#0F382A] text-white rounded-3xl p-6 md:p-7 border border-[#184F3B]"><div className="flex justify-between gap-5 flex-wrap"><div><span className="text-[10px] font-mono text-[#D4F55C] uppercase tracking-wider">{data.workspace.type} workspace</span><h2 className="font-serif text-2xl mt-1">{data.workspace.name}</h2><p className="text-sm text-[#B4CDC1] mt-2 max-w-2xl">{data.workspace.description}</p></div><div className="text-right"><div className="text-2xl font-serif text-[#D4F55C]">{data.workspace.members.length}</div><div className="text-xs text-[#B4CDC1]">active member{data.workspace.members.length === 1 ? '' : 's'}</div></div></div></section>
      <div className="grid grid-cols-2 lg:grid-cols-4 gap-4"><Metric label="shared items" value={String(data.inventory.totalItems)} detail={`${data.inventory.uniqueTypes} component types catalogued`} icon={Package}/><Metric label="reused components" value={String(data.activity.reusedComponents)} detail={`${data.activity.completedProjects} completed projects`} icon={ClipboardCheck}/><Metric label="estimated diversion" value={`${data.impact.massKg} kg`} detail={`${data.impact.coverage}% inventory coverage`} icon={Leaf}/><Metric label="estimated value" value={`$${data.inventory.reusableValue.toFixed(0)}`} detail={`$${data.impact.avoidedCost.toFixed(0)} avoided in recorded builds`} icon={DollarSign}/></div>
      <div className="grid lg:grid-cols-2 gap-5"><section className="bg-white rounded-3xl border border-[#E5EDE8] p-6 shadow-xs"><h2 className="font-serif text-lg text-[#11221B]">Inventory health</h2><p className="text-xs text-[#7E9187] mt-1">Quantities by component category</p><div className="space-y-3 mt-5">{Object.entries(data.inventory.categories).map(([name, quantity]) => <div key={name}><div className="flex justify-between text-xs"><span className="font-mono text-[#0F382A]">{name}</span><span className="text-[#5A6B63]">{quantity} items</span></div><div className="h-2 bg-[#F0F7F4] rounded-full mt-1 overflow-hidden"><div className="h-full bg-[#D4F55C] rounded-full" style={{width: `${quantity / maxCategory * 100}%`}} /></div></div>)}</div><details className="mt-5 text-xs"><summary className="cursor-pointer text-[#5A6B63]">View conditions as text</summary><div className="mt-2 text-[#5A6B63]">{Object.entries(data.inventory.conditions).map(([name, quantity]) => `${name}: ${quantity}`).join(' · ')}</div></details></section>
      <section className="bg-white rounded-3xl border border-[#E5EDE8] p-6 shadow-xs"><h2 className="font-serif text-lg text-[#11221B]">Lab activity</h2><p className="text-xs text-[#7E9187] mt-1">Meaningful logged actions, not individual ranking.</p><div className="space-y-3 mt-5">{data.activity.events.length ? data.activity.events.map((event, index) => <div key={index} className="flex gap-3 border-b border-[#F0F7F4] pb-3 last:border-0"><div className="w-7 h-7 shrink-0 rounded-lg bg-[#F0F7F4] text-[#0F382A] font-mono text-[10px] flex items-center justify-center">{event.quantity}</div><div><p className="text-xs text-[#11221B]">{event.detail}</p><p className="text-[10px] font-mono text-[#7E9187] mt-1">{new Date(event.date).toLocaleDateString()} · {event.type.replaceAll('_', ' ')}</p></div></div>) : <p className="text-sm text-[#7E9187] py-6">No reuse activity has been recorded yet.</p>}</div></section></div>
      <section className="bg-[#F8F7F2] rounded-3xl border border-[#EBE8DC] p-6"><div className="flex items-center gap-2"><Users className="w-4 h-4 text-[#0F382A]"/><h2 className="font-serif text-lg text-[#11221B]">Next steps for this lab</h2></div><div className="grid md:grid-cols-2 gap-3 mt-4">{data.recommendations.map((item, index) => <div key={item} className="bg-white rounded-2xl p-4 text-xs text-[#5A6B63] border border-[#E5EDE8]"><span className="font-mono text-[#0F382A] mr-2">0{index + 1}</span>{item}</div>)}</div><p className="text-[10px] text-[#7E9187] mt-4">Impact figures are estimates using methodology {data.impact.methodology}; they are not certified environmental measurements.</p></section></>}
  </div>;
}
